 steps:
#   # Step 1: Checkout the repository
#   - name: 'gcr.io/cloud-builders/git'
#     args: ['clone', 'https://github.com/your-repo.git']
#     dir: '/workspace'

  # Step 2: Build a Docker image and push it to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/dataproc-job:${SHORT_SHA}', '.']
    # dir: '/workspace'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/dataproc-job:${SHORT_SHA}']

  # Step 4: Replace the file in the bucket with the updated code
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', '-r', 'gs://your-bucket/updated-file.txt', '/workspace/path/to/file']
  #   dir: '/workspace'
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'artful-fragment-380106/github_amina8888_dataproc/main/main.py', 'gs://dataproc-repo-bucket/test.py']